# pubspec.yaml
name: uts_pemmob1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0' # Sesuaikan dengan versi SDK Anda

dependencies:
  flutter:
    sdk: flutter

  # Kriteria 7: State Management
  provider: ^6.0.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Kriteria 4 & 5: Assets dan Font
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700